version: '3.8'

networks:
  ec2-user_fqs_network:
    external: true

services:
  redis:
    image: redis:alpine
    command: redis-server --port 6379
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
    networks:
      - ec2-user_fqs_network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
    networks:
      - ec2-user_fqs_network

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - ec2-user_fqs_network

  eureka:
    image: kwforu/eureka:latest  # Docker Hub에 푸시한 Eureka 이미지
    ports:
      - "19090:19090"
    depends_on:
      - kafka
      - redis
    networks:
      - ec2-user_fqs_network

  gateway:
    image: kwforu/gateway_server:latest  # Docker Hub에 푸시한 Gateway 이미지
    ports:
      - "19091:19091"
    depends_on:
      - eureka
    networks:
      - ec2-user_fqs_network

  auth:
    image: kwforu/auth:latest  # Docker Hub에 푸시한 Auth 이미지
    ports:
      - "19092:19092"
    depends_on:
      - eureka
    networks:
      - ec2-user_fqs_network

  user:
    image: kwforu/user:latest  # Docker Hub에 푸시한 User 이미지
    ports:
      - "19093:19093"
    depends_on:
      - eureka
    networks:
      - ec2-user_fqs_network

  queue_manage:
    image: kwforu/queue_manage:latest  # Docker Hub에 푸시한 Queue Manage 이미지
    ports:
      - "19095:19095"
    depends_on:
      - eureka
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ec2-user_fqs_network

  queue:
    image: kwforu/queue:latest
    ports:
      - "19096:19096"
    depends_on:
      - eureka
    networks:
      - ec2-user_fqs_network