server:
  port: 19091

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  data:
    redis:
      host: localhost
      port: 6379
#      username: default
#      password: systempass
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
        - id: temporary-queue
          uri: lb://temporary-queue
          predicates:
            - Path=/temporary-queue/queue/**
        - id: queue-manage-service
          uri: lb://queue-manage-service
          predicates:
            - Path=/api/queue/**
      discovery:
        locator:
          enabled: true

service:
  jwt:
#    secret-key: "WnN3Q2FjQzRrNFl0V1d1TWp0RE5Xemw2RkE0WVYzS2VsR2xpUVF6M0x6dFNXbnc="
    secret-key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/