server:
  port: 19095

spring:
  application:
    name: queue-manage-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/fqs
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        hbm2ddl.auto: update
        default_batch_fetch_size: 100
    open-in-view: false
    show-sql: false
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  data:
    redis:
      host: redis
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health, info

eureka:
  client:
    service-url:
      defaultZone: http://eureka:19090/eureka/

docker:
  image-name: kwforu/queue

gateway:
  refresh-url: http://gateway:19091/routes/refresh-routes